In [5]:
import numpy as np
import pandas as pd
from yaml import safe_load
import os
from tqdm import tqdm

In [6]:
filenames = []
for file in os.listdir('data'):
    filenames.append(os.path.join('data',file))

In [7]:
filenames[0:5]

['data\\1046679.yaml',
 'data\\1046681.yaml',
 'data\\1046685.yaml',
 'data\\1046687.yaml',
 'data\\1049617.yaml']

In [ ]:
import pandas as pd
from tqdm import tqdm
from yaml import safe_load  # assuming the files are YAML/JSON compatible

final_df = pd.DataFrame()
counter = 1

for file in tqdm(filenames):
    with open(file, 'r') as f:
        data = safe_load(f)
        df = pd.json_normalize(data)
        df['match_id'] = counter
        final_df = pd.concat([final_df, df], ignore_index=True)
        counter += 1

final_df

 72%|███████▏  | 234/325 [00:40<00:19,  4.62it/s]

In [ ]:
backup = final_df.copy()

In [ ]:
final_df

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.city,info.dates,info.gender,info.match_type,info.neutral_venue,...,info.registry.people.Obaydul Haque,info.registry.people.AAhan Achar,info.registry.people.Abhinav Raman,info.registry.people.D Sevakumaran,info.registry.people.K Suresh,info.registry.people.Fikri Makram,info.registry.people.NMS Param,info.registry.people.R Rohan,info.registry.people.U Rakshit,info.registry.people.V Kadiresan
0,"[{'1st innings': {'team': 'Gibraltar', 'delive...",0.91,2016-08-19,1,6.0,Stockholm,[2016-08-17],male,IT20,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Germany', 'deliveri...",0.91,2016-08-19,1,6.0,Stockholm,[2016-08-17],male,IT20,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Gibraltar', 'delive...",0.91,2016-08-19,1,6.0,Stockholm,[2016-08-17],male,IT20,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Israel', 'deliverie...",0.91,2016-08-19,1,6.0,Stockholm,[2016-08-17],male,IT20,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Singapore', 'delive...",0.91,2016-08-31,2,6.0,NaN,[2016-08-26],female,IT20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.91,2015-12-07,2,6.0,Bangkok,[2015-12-05],female,IT20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,"[{'1st innings': {'team': 'Scotland', 'deliver...",0.91,2015-12-07,2,6.0,Bangkok,[2015-12-05],female,IT20,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",0.91,2015-11-18,3,6.0,Cox's Bazar,[2015-11-17],female,IT20,NaN,...,26cd0ae9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
322,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.91,2015-11-19,2,6.0,Cox's Bazar,[2015-11-19],female,IT20,NaN,...,26cd0ae9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,"[{'1st innings': {'team': 'Malaysia', 'deliver...",0.91,2016-02-23,4,6.0,Kuala Lumpur,[2016-02-21],male,IT20,NaN,...,NaN,797f52cc,0cb292b1,b235cb97,1b01ab7d,2aa49a9a,270b4de6,baf0fc26,f6b39059,ae84d864

In [ ]:
final_df.drop(columns=[
    'meta.data_version',
    'meta.created',
    'meta.revision',
    'info.outcome.result',
    'info.outcome.method',
    'info.neutral_venue',
    'info.outcome.by.runs',
    'info.outcome.by.wickets'
],inplace=True)

In [ ]:
final_df

,innings,info.balls_per_over,info.city,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.players.Gibraltar,info.players.Israel,...,info.registry.people.Obaydul Haque,info.registry.people.AAhan Achar,info.registry.people.Abhinav Raman,info.registry.people.D Sevakumaran,info.registry.people.K Suresh,info.registry.people.Fikri Makram,info.registry.people.NMS Param,info.registry.people.R Rohan,info.registry.people.U Rakshit,info.registry.people.V Kadiresan
0,"[{'1st innings': {'team': 'Gibraltar', 'delive...",6.0,Stockholm,[2016-08-17],male,IT20,Israel,20,"[KJ Ferrary, MO Bacarese, K Aswani, IDM Latin,...","[SRM Arachichige, M Hoffman, E Kahamker, Emanu...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Germany', 'deliveri...",6.0,Stockholm,[2016-08-17],male,IT20,Germany,20,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Gibraltar', 'delive...",6.0,Stockholm,[2016-08-17],male,IT20,Isle of Man,20,"[MO Bacarese, KJ Ferrary, K Aswani, IDM Latin,...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Israel', 'deliverie...",6.0,Stockholm,[2016-08-17],male,IT20,Spain,20,NaN,"[SRM Arachichige, M Hoffman, Emanuel Solomon, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Singapore', 'delive...",6.0,NaN,[2016-08-26],female,IT20,Singapore,20,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,"[{'1st innings': {'team': 'Netherlands', 'deli...",6.0,Bangkok,[2015-12-05],female,IT20,Thailand,20,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,"[{'1st innings': {'team': 'Scotland', 'deliver...",6.0,Bangkok,[2015-12-05],female,IT20,Zimbabwe,20,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",6.0,Cox's Bazar,[2015-11-17],female,IT20,Bangladesh,20,NaN,NaN,...,26cd0ae9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
322,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",6.0,Cox's Bazar,[2015-11-19],female,IT20,Bangladesh,20,NaN,NaN,...,26cd0ae9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,"[{'1st innings': {'team': 'Malaysia', 'deliver...",6.0,Kuala Lumpur,[2016-02-21],male,IT20,Malaysia,20,NaN,NaN,...,NaN,797f52cc,0cb292b1,b235cb97,1b01ab7d,2aa49a9a,270b4de6,baf0fc26,f6b39059,ae84d864

In [ ]:
final_df.shape

(243, 1912)

In [ ]:
final_df['info.gender'].value_counts()

info.gender
male      244
female     80
Name: count, dtype: int64

In [ ]:
final_df=final_df[final_df['info.gender']=='male']

In [ ]:
df['info.match_type'].value_counts()

info.match_type
IT20    1
Name: count, dtype: int64

In [ ]:
final_df['info.overs'].value_counts()

info.overs
20    243
50      1
Name: count, dtype: int64

In [ ]:
final_df=final_df[final_df['info.overs']==20]

In [ ]:
final_df.shape

(243, 1912)

In [ ]:
final_df = final_df[['innings', 
                     'info.dates', 
                     'info.match_type', 
                     'info.outcome.winner', 
                     'info.overs', 
                     'info.player_of_match', 
                     'info.teams', 
                     'info.toss.decision', 
                     'info.toss.winner', 
                     'info.umpires', 
                     'info.venue', 
                     'match_id', 
                     'info.city']]

In [ ]:
matches=final_df.copy()

In [ ]:
matches.iloc[0]['innings'][0]['1st innings']['deliveries']

[{0.1: {'batsman': 'KJ Ferrary',
   'bowler': 'D Massil',
   'non_striker': 'MO Bacarese',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {0.2: {'batsman': 'MO Bacarese',
   'bowler': 'D Massil',
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.3: {'batsman': 'MO Bacarese',
   'bowler': 'D Massil',
   'extras': {'wides': 1},
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {0.4: {'batsman': 'MO Bacarese',
   'bowler': 'D Massil',
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {0.5: {'batsman': 'MO Bacarese',
   'bowler': 'D Massil',
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.6: {'batsman': 'MO Bacarese',
   'bowler': 'D Massil',
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.7: {'batsman': 'MO Bacarese',
   'bowler': 'D Massil',
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {1.1: {'batsman': 'MO Bacarese',
   'bowler': 'S Waskar',
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.2: {'batsman': 'MO Bacarese',
   'bowler': 'S Waskar',
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {1.3: {'batsman': 'MO Bacarese',
   'bowler': 'S Waskar',
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {1.4: {'batsman': 'KJ Ferrary',
   'bowler': 'S Waskar',
   'non_striker': 'MO Bacarese',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.5: {'batsman': 'KJ Ferrary',
   'bowler': 'S Waskar',
   'non_striker': 'MO Bacarese',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.6: {'batsman': 'KJ Ferrary',
   'bowler': 'S Waskar',
   'non_striker': 'MO Bacarese',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.1: {'batsman': 'MO Bacarese',
   'bowler': 'D Massil',
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.2: {'batsman': 'MO Bacarese',
   'bowler': 'D Massil',
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.3: {'batsman': 'KJ Ferrary',
   'bowler': 'D Massil',
   'non_striker': 'MO Bacarese',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {2.4: {'batsman': 'KJ Ferrary',
   'bowler': 'D Massil',
   'non_striker': 'MO Bacarese',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.5: {'batsman': 'MO Bacarese',
   'bowler': 'D Massil',
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.6: {'batsman': 'MO Bacarese',
   'bowler': 'D Massil',
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.1: {'batsman': 'KJ Ferrary',
   'bowler': 'S Waskar',
   'non_striker': 'MO Bacarese',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.2: {'batsman': 'KJ Ferrary',
   'bowler': 'S Waskar',
   'non_striker': 'MO Bacarese',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.3: {'batsman': 'MO Bacarese',
   'bowler': 'S Waskar',
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.4: {'batsman': 'KJ Ferrary',
   'bowler': 'S Waskar',
   'non_striker': 'MO Bacarese',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {3.5: {'batsman': 'KJ Ferrary',
   'bowler': 'S Waskar',
   'non_striker': 'MO Bacarese',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.6: {'batsman': 'KJ Ferrary',
   'bowler': 'S Waskar',
   'non_striker': 'MO Bacarese',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {4.1: {'batsman': 'MO Bacarese',
   'bowler': 'SRM Arachichige',
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {4.2: {'batsman': 'MO Bacarese',
   'bowler': 'SRM Arachichige',
   'non_striker': 'KJ Ferrary',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['E Solomon'],
    'kind': 'caught',
    'player_out': 'MO Bacarese'}}},
 {4.3: {'batsman': 'KJ Ferrary',
   'bowler': 'SRM Arachichige',
   'non_striker': 'K Aswani',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {4.4: {'batsman': 'KJ Ferrary',
   'bowler': 'SRM Arachichige',
   'non_striker': 'K Aswani',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {4.5: {'batsman': 'KJ Ferrary',
   'bowler': 'SRM Arachichige',
   'non_striker': 'K Aswani',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {4.6: {'batsman': 'KJ Ferrary',
   'bowler': 'SRM Arachichige',
   'non_striker': 'K Aswani',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['S Bangera'],
    'kind': 'caught',
    'player_out': 'KJ Ferrary'}}},
 {5.1: {'batsman': 'K Aswani',
   'bowler': 'E Kahamker',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.2: {'batsman': 'IDM Latin',
   'bowler': 'E Kahamker',
   'non_striker': 'K Aswani',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.3: {'batsman': 'K Aswani',
   'bowler': 'E Kahamker',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.4: {'batsman': 'K Aswani',
   'bowler': 'E Kahamker',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.5: {'batsman': 'K Aswani',
   'bowler': 'E Kahamker',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {5.6: {'batsman': 'K Aswani',
   'bowler': 'E Kahamker',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {6.1: {'batsman': 'IDM Latin',
   'bowler': 'SRM Arachichige',
   'non_striker': 'K Aswani',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {6.2: {'batsman': 'IDM Latin',
   'bowler': 'SRM Arachichige',
   'non_striker': 'K Aswani',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.3: {'batsman': 'K Aswani',
   'bowler': 'SRM Arachichige',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {6.4: {'batsman': 'K Aswani',
   'bowler': 'SRM Arachichige',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'kind': 'lbw', 'player_out': 'K Aswani'}}},
 {6.5: {'batsman': 'CJ Phillips',
   'bowler': 'SRM Arachichige',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {6.6: {'batsman': 'CJ Phillips',
   'bowler': 'SRM Arachichige',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {7.1: {'batsman': 'IDM Latin',
   'bowler': 'E Kahamker',
   'non_striker': 'CJ Phillips',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {7.2: {'batsman': 'IDM Latin',
   'bowler': 'E Kahamker',
   'non_striker': 'CJ Phillips',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.3: {'batsman': 'CJ Phillips',
   'bowler': 'E Kahamker',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {7.4: {'batsman': 'CJ Phillips',
   'bowler': 'E Kahamker',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.5: {'batsman': 'IDM Latin',
   'bowler': 'E Kahamker',
   'non_striker': 'CJ Phillips',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {7.6: {'batsman': 'IDM Latin',
   'bowler': 'E Kahamker',
   'non_striker': 'CJ Phillips',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.1: {'batsman': 'CJ Phillips',
   'bowler': 'SRM Arachichige',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.2: {'batsman': 'IDM Latin',
   'bowler': 'SRM Arachichige',
   'extras': {'legbyes': 1},
   'non_striker': 'CJ Phillips',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {8.3: {'batsman': 'CJ Phillips',
   'bowler': 'SRM Arachichige',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.4: {'batsman': 'CJ Phillips',
   'bowler': 'SRM Arachichige',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.5: {'batsman': 'CJ Phillips',
   'bowler': 'SRM Arachichige',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.6: {'batsman': 'CJ Phillips',
   'bowler': 'SRM Arachichige',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.1: {'batsman': 'CJ Phillips',
   'bowler': 'R Schachat',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.2: {'batsman': 'IDM Latin',
   'bowler': 'R Schachat',
   'non_striker': 'CJ Phillips',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.3: {'batsman': 'CJ Phillips',
   'bowler': 'R Schachat',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {9.4: {'batsman': 'CJ Phillips',
   'bowler': 'R Schachat',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {9.5: {'batsman': 'CJ Phillips',
   'bowler': 'R Schachat',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.6: {'batsman': 'IDM Latin',
   'bowler': 'R Schachat',
   'non_striker': 'CJ Phillips',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.1: {'batsman': 'CJ Phillips',
   'bowler': 'J Evans',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.2: {'batsman': 'CJ Phillips',
   'bowler': 'J Evans',
   'extras': {'noballs': 1},
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {10.3: {'batsman': 'CJ Phillips',
   'bowler': 'J Evans',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.4: {'batsman': 'IDM Latin',
   'bowler': 'J Evans',
   'non_striker': 'CJ Phillips',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.5: {'batsman': 'IDM Latin',
   'bowler': 'J Evans',
   'non_striker': 'CJ Phillips',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.6: {'batsman': 'CJ Phillips',
   'bowler': 'J Evans',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {10.7: {'batsman': 'CJ Phillips',
   'bowler': 'J Evans',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.1: {'batsman': 'CJ Phillips',
   'bowler': 'R Schachat',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {11.2: {'batsman': 'CJ Phillips',
   'bowler': 'R Schachat',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {11.3: {'batsman': 'CJ Phillips',
   'bowler': 'R Schachat',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {11.4: {'batsman': 'CJ Phillips',
   'bowler': 'R Schachat',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {11.5: {'batsman': 'CJ Phillips',
   'bowler': 'R Schachat',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {11.6: {'batsman': 'CJ Phillips',
   'bowler': 'R Schachat',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {12.1: {'batsman': 'IDM Latin',
   'bowler': 'J Evans',
   'extras': {'wides': 1},
   'non_striker': 'CJ Phillips',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {12.2: {'batsman': 'IDM Latin',
   'bowler': 'J Evans',
   'non_striker': 'CJ Phillips',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.3: {'batsman': 'CJ Phillips',
   'bowler': 'J Evans',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['Y Razpurker'],
    'kind': 'caught',
    'player_out': 'CJ Phillips'}}},
 {12.4: {'batsman': 'IDM Latin',
   'bowler': 'J Evans',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.5: {'batsman': 'K Mirpuri',
   'bowler': 'J Evans',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {12.6: {'batsman': 'K Mirpuri',
   'bowler': 'J Evans',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {12.7: {'batsman': 'K Mirpuri',
   'bowler': 'J Evans',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.1: {'batsman': 'K Mirpuri',
   'bowler': 'Y Razpurker',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {13.2: {'batsman': 'K Mirpuri',
   'bowler': 'Y Razpurker',
   'extras': {'wides': 1},
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {13.3: {'batsman': 'K Mirpuri',
   'bowler': 'Y Razpurker',
   'extras': {'wides': 1},
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {13.4: {'batsman': 'K Mirpuri',
   'bowler': 'Y Razpurker',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {13.5: {'batsman': 'K Mirpuri',
   'bowler': 'Y Razpurker',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.6: {'batsman': 'IDM Latin',
   'bowler': 'Y Razpurker',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {13.7: {'batsman': 'IDM Latin',
   'bowler': 'Y Razpurker',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.8: {'batsman': 'K Mirpuri',
   'bowler': 'Y Razpurker',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {14.1: {'batsman': 'IDM Latin',
   'bowler': 'J Evans',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.2: {'batsman': 'K Mirpuri',
   'bowler': 'J Evans',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {14.3: {'batsman': 'K Mirpuri',
   'bowler': 'J Evans',
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {14.4: {'batsman': 'K Mirpuri',
   'bowler': 'J Evans',
   'extras': {'legbyes': 1},
   'non_striker': 'IDM Latin',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {14.5: {'batsman': 'IDM Latin',
   'bowler': 'J Evans',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'kind': 'bowled', 'player_out': 'IDM Latin'}}},
 {14.6: {'batsman': 'JD Freyone',
   'bowler': 'J Evans',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {15.1: {'batsman': 'K Mirpuri',
   'bowler': 'Y Razpurker',
   'non_striker': 'JD Freyone',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.2: {'batsman': 'JD Freyone',
   'bowler': 'Y Razpurker',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {15.3: {'batsman': 'JD Freyone',
   'bowler': 'Y Razpurker',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.4: {'batsman': 'K Mirpuri',
   'bowler': 'Y Razpurker',
   'non_striker': 'JD Freyone',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {15.5: {'batsman': 'K Mirpuri',
   'bowler': 'Y Razpurker',
   'non_striker': 'JD Freyone',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {15.6: {'batsman': 'K Mirpuri',
   'bowler': 'Y Razpurker',
   'non_striker': 'JD Freyone',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.1: {'batsman': 'K Mirpuri',
   'bowler': 'J Evans',
   'non_striker': 'JD Freyone',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.2: {'batsman': 'JD Freyone',
   'bowler': 'J Evans',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {16.3: {'batsman': 'JD Freyone',
   'bowler': 'J Evans',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {16.4: {'batsman': 'JD Freyone',
   'bowler': 'J Evans',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {16.5: {'batsman': 'JD Freyone',
   'bowler': 'J Evans',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.6: {'batsman': 'K Mirpuri',
   'bowler': 'J Evans',
   'non_striker': 'JD Freyone',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.1: {'batsman': 'K Mirpuri',
   'bowler': 'R Schachat',
   'non_striker': 'JD Freyone',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {17.2: {'batsman': 'K Mirpuri',
   'bowler': 'R Schachat',
   'non_striker': 'JD Freyone',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {17.3: {'batsman': 'K Mirpuri',
   'bowler': 'R Schachat',
   'non_striker': 'JD Freyone',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {17.4: {'batsman': 'K Mirpuri',
   'bowler': 'R Schachat',
   'non_striker': 'JD Freyone',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.5: {'batsman': 'JD Freyone',
   'bowler': 'R Schachat',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {17.6: {'batsman': 'JD Freyone',
   'bowler': 'R Schachat',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {18.1: {'batsman': 'K Mirpuri',
   'bowler': 'SRM Arachichige',
   'non_striker': 'JD Freyone',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {18.2: {'batsman': 'JD Freyone',
   'bowler': 'SRM Arachichige',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {18.3: {'batsman': 'K Mirpuri',
   'bowler': 'SRM Arachichige',
   'non_striker': 'JD Freyone',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {18.4: {'batsman': 'K Mirpuri',
   'bowler': 'SRM Arachichige',
   'non_striker': 'JD Freyone',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {18.5: {'batsman': 'JD Freyone',
   'bowler': 'SRM Arachichige',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {18.6: {'batsman': 'JD Freyone',
   'bowler': 'SRM Arachichige',
   'extras': {'wides': 1},
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {18.7: {'batsman': 'JD Freyone',
   'bowler': 'SRM Arachichige',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['S Bangera'],
    'kind': 'caught',
    'player_out': 'JD Freyone'}}},
 {19.1: {'batsman': 'K Mirpuri',
   'bowler': 'R Schachat',
   'non_striker': 'J Hazell',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {19.2: {'batsman': 'K Mirpuri',
   'bowler': 'R Schachat',
   'non_striker': 'J Hazell',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {19.3: {'batsman': 'K Mirpuri',
   'bowler': 'R Schachat',
   'non_striker': 'J Hazell',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.4: {'batsman': 'J Hazell',
   'bowler': 'R Schachat',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.5: {'batsman': 'K Mirpuri',
   'bowler': 'R Schachat',
   'non_striker': 'J Hazell',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.6: {'batsman': 'J Hazell',
   'bowler': 'R Schachat',
   'non_striker': 'K Mirpuri',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}}]

In [ ]:
import pandas as pd

skip_matches = [75, 108, 150, 180, 268, 360, 443, 458, 584, 748, 982, 1052, 1111, 1226, 1345]
delivery_data = []

for _, row in matches.iterrows():
    match_id = row['match_id']
    if match_id in skip_matches:
        continue
    
    try:
        deliveries = row['innings'][0]['1st innings']['deliveries']
        batting_team = row['innings'][0]['1st innings']['team']
    except (KeyError, IndexError, TypeError):
        continue  # Skip malformed records

    for delivery in deliveries:
        for ball, detail in delivery.items():
            delivery_data.append({
                'match_id': match_id,
                'teams': row.get('info.teams', []),
                'batting_team': batting_team,
                'ball': ball,
                'batsman': detail.get('batsman'),
                'bowler': detail.get('bowler'),
                'runs': detail.get('runs', {}).get('total', 0),
                'player_dismissed': detail.get('wicket', {}).get('player_out', None),
                'city': row.get('info.city'),
                'venue': row.get('info.venue')
            })

delivery_df = pd.DataFrame(delivery_data)

In [ ]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,1,"[Gibraltar, Israel]",Gibraltar,0.1,KJ Ferrary,D Massil,1,None,Stockholm,Skarpnack 1
1,1,"[Gibraltar, Israel]",Gibraltar,0.2,MO Bacarese,D Massil,0,None,Stockholm,Skarpnack 1
2,1,"[Gibraltar, Israel]",Gibraltar,0.3,MO Bacarese,D Massil,1,None,Stockholm,Skarpnack 1
3,1,"[Gibraltar, Israel]",Gibraltar,0.4,MO Bacarese,D Massil,4,None,Stockholm,Skarpnack 1
4,1,"[Gibraltar, Israel]",Gibraltar,0.5,MO Bacarese,D Massil,0,None,Stockholm,Skarpnack 1
...,...,...,...,...,...,...,...,...,...,...
28696,324,"[Malaysia, Singapore]",Malaysia,19.2,Shafiq Sharif,AAhan Achar,4,None,Kuala Lumpur,Kinrara Academy Oval
28697,324,"[Malaysia, Singapore]",Malaysia,19.3,Shafiq Sharif,AAhan Achar,1,None,Kuala Lumpur,Kinrara Academy Oval
28698,324,"[Malaysia, Singapore]",Malaysia,19.4,Ahmed Faiz Mohammad Noor,AAhan Achar,6,None,Kuala Lumpur,Kinrara Academy Oval
28699,324,"[Malaysia, Singapore]",Malaysia,19.5,Ahmed Faiz Mohammad Noor,AAhan Achar,1,None,Kuala Lumpur,Kinrara Academy Oval
28700,324,"[Malaysia, Singapore]",Malaysia,19.6,Shafiq Sharif,AAhan Achar,4,None,Kuala Lumpur,Kinrara Academy Oval

In [ ]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,1,"[Gibraltar, Israel]",Gibraltar,0.1,KJ Ferrary,D Massil,1,None,Stockholm,Skarpnack 1
1,1,"[Gibraltar, Israel]",Gibraltar,0.2,MO Bacarese,D Massil,0,None,Stockholm,Skarpnack 1
2,1,"[Gibraltar, Israel]",Gibraltar,0.3,MO Bacarese,D Massil,1,None,Stockholm,Skarpnack 1
3,1,"[Gibraltar, Israel]",Gibraltar,0.4,MO Bacarese,D Massil,4,None,Stockholm,Skarpnack 1
4,1,"[Gibraltar, Israel]",Gibraltar,0.5,MO Bacarese,D Massil,0,None,Stockholm,Skarpnack 1
...,...,...,...,...,...,...,...,...,...,...
28696,324,"[Malaysia, Singapore]",Malaysia,19.2,Shafiq Sharif,AAhan Achar,4,None,Kuala Lumpur,Kinrara Academy Oval
28697,324,"[Malaysia, Singapore]",Malaysia,19.3,Shafiq Sharif,AAhan Achar,1,None,Kuala Lumpur,Kinrara Academy Oval
28698,324,"[Malaysia, Singapore]",Malaysia,19.4,Ahmed Faiz Mohammad Noor,AAhan Achar,6,None,Kuala Lumpur,Kinrara Academy Oval
28699,324,"[Malaysia, Singapore]",Malaysia,19.5,Ahmed Faiz Mohammad Noor,AAhan Achar,1,None,Kuala Lumpur,Kinrara Academy Oval
28700,324,"[Malaysia, Singapore]",Malaysia,19.6,Shafiq Sharif,AAhan Achar,4,None,Kuala Lumpur,Kinrara Academy Oval

In [ ]:
def bowl(row):
    for team in row['teams']:
        if team != row['batting_team']:
            return team

In [ ]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,1,"[Gibraltar, Israel]",Gibraltar,0.1,KJ Ferrary,D Massil,1,None,Stockholm,Skarpnack 1
1,1,"[Gibraltar, Israel]",Gibraltar,0.2,MO Bacarese,D Massil,0,None,Stockholm,Skarpnack 1
2,1,"[Gibraltar, Israel]",Gibraltar,0.3,MO Bacarese,D Massil,1,None,Stockholm,Skarpnack 1
3,1,"[Gibraltar, Israel]",Gibraltar,0.4,MO Bacarese,D Massil,4,None,Stockholm,Skarpnack 1
4,1,"[Gibraltar, Israel]",Gibraltar,0.5,MO Bacarese,D Massil,0,None,Stockholm,Skarpnack 1
...,...,...,...,...,...,...,...,...,...,...
28696,324,"[Malaysia, Singapore]",Malaysia,19.2,Shafiq Sharif,AAhan Achar,4,None,Kuala Lumpur,Kinrara Academy Oval
28697,324,"[Malaysia, Singapore]",Malaysia,19.3,Shafiq Sharif,AAhan Achar,1,None,Kuala Lumpur,Kinrara Academy Oval
28698,324,"[Malaysia, Singapore]",Malaysia,19.4,Ahmed Faiz Mohammad Noor,AAhan Achar,6,None,Kuala Lumpur,Kinrara Academy Oval
28699,324,"[Malaysia, Singapore]",Malaysia,19.5,Ahmed Faiz Mohammad Noor,AAhan Achar,1,None,Kuala Lumpur,Kinrara Academy Oval
28700,324,"[Malaysia, Singapore]",Malaysia,19.6,Shafiq Sharif,AAhan Achar,4,None,Kuala Lumpur,Kinrara Academy Oval

In [ ]:
delivery_df['bowling_team'] = delivery_df.apply(bowl,axis=1)

In [ ]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,1,"[Gibraltar, Israel]",Gibraltar,0.1,KJ Ferrary,D Massil,1,None,Stockholm,Skarpnack 1,Israel
1,1,"[Gibraltar, Israel]",Gibraltar,0.2,MO Bacarese,D Massil,0,None,Stockholm,Skarpnack 1,Israel
2,1,"[Gibraltar, Israel]",Gibraltar,0.3,MO Bacarese,D Massil,1,None,Stockholm,Skarpnack 1,Israel
3,1,"[Gibraltar, Israel]",Gibraltar,0.4,MO Bacarese,D Massil,4,None,Stockholm,Skarpnack 1,Israel
4,1,"[Gibraltar, Israel]",Gibraltar,0.5,MO Bacarese,D Massil,0,None,Stockholm,Skarpnack 1,Israel
...,...,...,...,...,...,...,...,...,...,...,...
28696,324,"[Malaysia, Singapore]",Malaysia,19.2,Shafiq Sharif,AAhan Achar,4,None,Kuala Lumpur,Kinrara Academy Oval,Singapore
28697,324,"[Malaysia, Singapore]",Malaysia,19.3,Shafiq Sharif,AAhan Achar,1,None,Kuala Lumpur,Kinrara Academy Oval,Singapore
28698,324,"[Malaysia, Singapore]",Malaysia,19.4,Ahmed Faiz Mohammad Noor,AAhan Achar,6,None,Kuala Lumpur,Kinrara Academy Oval,Singapore
28699,324,"[Malaysia, Singapore]",Malaysia,19.5,Ahmed Faiz Mohammad Noor,AAhan Achar,1,None,Kuala Lumpur,Kinrara Academy Oval,Singapore
28700,324,"[Malaysia, Singapore]",Malaysia,19.6,Shafiq Sharif,AAhan Achar,4,None,Kuala Lumpur,Kinrara Academy Oval,Singapore

In [ ]:
delivery_df.drop(columns=['teams'],inplace=True)

In [ ]:
delivery_df['batting_team'].unique()

array(['Gibraltar', 'Germany', 'Israel', 'Saudi Arabia', 'Uganda',
       'Kenya', 'China', 'Namibia', 'Kuwait', 'Bahrain', 'Qatar',
       'Maldives', 'United Arab Emirates', 'Nigeria', 'Ghana', 'Gambia',
       'Tanzania', 'Rwanda', 'Vanuatu', 'Papua New Guinea', 'Samoa',
       'Fiji', 'France', 'Portugal', 'Austria', 'Denmark', 'Cyprus',
       'Isle of Man', 'Finland', 'Spain', 'Italy', 'Jersey', 'Belgium',
       'Norway', 'Sweden', 'Guernsey', 'Panama', 'Belize',
       'United States of America', 'Canada', 'Japan', 'Myanmar',
       'Malaysia', 'Singapore', 'Nepal', 'Thailand', 'Swaziland',
       'St Helena', 'Botswana', 'Mozambique', 'Malawi', 'Lesotho',
       'Philippines', 'Indonesia', 'Argentina', 'Cayman Islands',
       'Bermuda', 'Ireland', 'Hong Kong', 'Scotland', 'South Korea',
       'Sri Lanka', 'Bangladesh', 'Oman', 'Netherlands'], dtype=object)

In [ ]:
teams = [
    'Australia',
    'India',
    'Bangladesh',
    'New Zealand',
    'South Africa',
    'England',
    'West Indies',
    'Afghanistan',
    'Pakistan',
    'Sri Lanka'    
]

In [ ]:
delivery_df

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,1,Gibraltar,0.1,KJ Ferrary,D Massil,1,None,Stockholm,Skarpnack 1,Israel
1,1,Gibraltar,0.2,MO Bacarese,D Massil,0,None,Stockholm,Skarpnack 1,Israel
2,1,Gibraltar,0.3,MO Bacarese,D Massil,1,None,Stockholm,Skarpnack 1,Israel
3,1,Gibraltar,0.4,MO Bacarese,D Massil,4,None,Stockholm,Skarpnack 1,Israel
4,1,Gibraltar,0.5,MO Bacarese,D Massil,0,None,Stockholm,Skarpnack 1,Israel
...,...,...,...,...,...,...,...,...,...,...
28696,324,Malaysia,19.2,Shafiq Sharif,AAhan Achar,4,None,Kuala Lumpur,Kinrara Academy Oval,Singapore
28697,324,Malaysia,19.3,Shafiq Sharif,AAhan Achar,1,None,Kuala Lumpur,Kinrara Academy Oval,Singapore
28698,324,Malaysia,19.4,Ahmed Faiz Mohammad Noor,AAhan Achar,6,None,Kuala Lumpur,Kinrara Academy Oval,Singapore
28699,324,Malaysia,19.5,Ahmed Faiz Mohammad Noor,AAhan Achar,1,None,Kuala Lumpur,Kinrara Academy Oval,Singapore
28700,324,Malaysia,19.6,Shafiq Sharif,AAhan Achar,4,None,Kuala Lumpur,Kinrara Academy Oval,Singapore

In [ ]:

delivery_df = delivery_df[delivery_df['batting_team'].isin(teams)]
delivery_df = delivery_df[delivery_df['bowling_team'].isin(teams)]

In [ ]:
delivery_df

Empty DataFrame
Columns: [match_id, batting_team, ball, batsman, bowler, runs, player_dismissed, city, venue, bowling_team]
Index: []

In [ ]:
output = delivery_df[['match_id','batting_team','bowling_team','ball','runs','player_dismissed','city','venue']]

In [ ]:
output.head(4)

Empty DataFrame
Columns: [match_id, batting_team, bowling_team, ball, runs, player_dismissed, city, venue]
Index: []