In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:

df = pd.read_csv(
    "mymoviedb.csv",
    sep=",",
    engine="python",
    on_bad_lines="skip",  
    encoding="utf-8"
)

df

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...
...,...,...,...,...,...,...,...,...,...
9832,1973-10-15,Badlands,A dramatization of the Starkweather-Fugate kil...,13.357,896,7.6,en,"Drama, Crime",https://image.tmdb.org/t/p/original/z81rBzHNgi...
9833,2020-10-01,Violent Delights,A female vampire falls in love with a man she ...,13.356,8,3.5,es,Horror,https://image.tmdb.org/t/p/original/4b6HY7rud6...
9834,2016-05-06,The Offering,When young and successful reporter Jamie finds...,13.355,94,5.0,en,"Mystery, Thriller, Horror",https://image.tmdb.org/t/p/original/h4uMM1wOhz...
9835,2021-03-31,The United States vs. Billie Holiday,Billie Holiday spent much of her career being ...,13.354,152,6.7,en,"Music, Drama, History",https://image.tmdb.org/t/p/original/vEzkxuE2sJ...
9836,1984-09-23,Threads,Documentary style account of a nuclear holocau...,13.354,186,7.8,en,"War, Drama, Science Fiction",https://image.tmdb.org/t/p/original/lBhU4U9Eeh...

In [3]:
df=df.drop(columns=['Overview','Poster_Url','Original_Language'])

In [4]:
df

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021-12-15,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction"
1,2022-03-01,The Batman,3827.658,1151,8.1,"Crime, Mystery, Thriller"
2,2022-02-25,No Exit,2618.087,122,6.3,Thriller
3,2021-11-24,Encanto,2402.201,5076,7.7,"Animation, Comedy, Family, Fantasy"
4,2021-12-22,The King's Man,1895.511,1793,7.0,"Action, Adventure, Thriller, War"
...,...,...,...,...,...,...
9832,1973-10-15,Badlands,13.357,896,7.6,"Drama, Crime"
9833,2020-10-01,Violent Delights,13.356,8,3.5,Horror
9834,2016-05-06,The Offering,13.355,94,5.0,"Mystery, Thriller, Horror"
9835,2021-03-31,The United States vs. Billie Holiday,13.354,152,6.7,"Music, Drama, History"
9836,1984-09-23,Threads,13.354,186,7.8,"War, Drama, Science Fiction"

In [5]:
df.isnull().sum()

Release_Date     0
Title            9
Popularity      10
Vote_Count      10
Vote_Average    10
Genre           11
dtype: int64

In [6]:
df.shape

(9837, 6)

In [7]:
df.dropna(inplace=True)

In [8]:
df.isnull().sum()

Release_Date    0
Title           0
Popularity      0
Vote_Count      0
Vote_Average    0
Genre           0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.drop_duplicates()

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021-12-15,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction"
1,2022-03-01,The Batman,3827.658,1151,8.1,"Crime, Mystery, Thriller"
2,2022-02-25,No Exit,2618.087,122,6.3,Thriller
3,2021-11-24,Encanto,2402.201,5076,7.7,"Animation, Comedy, Family, Fantasy"
4,2021-12-22,The King's Man,1895.511,1793,7.0,"Action, Adventure, Thriller, War"
...,...,...,...,...,...,...
9832,1973-10-15,Badlands,13.357,896,7.6,"Drama, Crime"
9833,2020-10-01,Violent Delights,13.356,8,3.5,Horror
9834,2016-05-06,The Offering,13.355,94,5.0,"Mystery, Thriller, Horror"
9835,2021-03-31,The United States vs. Billie Holiday,13.354,152,6.7,"Music, Drama, History"
9836,1984-09-23,Threads,13.354,186,7.8,"War, Drama, Science Fiction"

In [11]:
df.describe()

        Popularity
count  9826.000000
mean     40.323951
std     108.879332
min      13.354000
25%      16.128250
50%      21.195000
75%      35.179250
max    5083.954000

In [12]:
df['Release_Date']= pd.to_datetime(df['Release_Date'])

In [13]:
df['Release_Date']= df['Release_Date'].dt.year

df['Release_Date']

0       2021
1       2022
2       2022
3       2021
4       2021
        ...
9832    1973
9833    2020
9834    2016
9835    2021
9836    1984
Name: Release_Date, Length: 9826, dtype: int32

In [14]:
df

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction"
1,2022,The Batman,3827.658,1151,8.1,"Crime, Mystery, Thriller"
2,2022,No Exit,2618.087,122,6.3,Thriller
3,2021,Encanto,2402.201,5076,7.7,"Animation, Comedy, Family, Fantasy"
4,2021,The King's Man,1895.511,1793,7.0,"Action, Adventure, Thriller, War"
...,...,...,...,...,...,...
9832,1973,Badlands,13.357,896,7.6,"Drama, Crime"
9833,2020,Violent Delights,13.356,8,3.5,Horror
9834,2016,The Offering,13.355,94,5.0,"Mystery, Thriller, Horror"
9835,2021,The United States vs. Billie Holiday,13.354,152,6.7,"Music, Drama, History"
9836,1984,Threads,13.354,186,7.8,"War, Drama, Science Fiction"

In [15]:
df['Release_Date'].value_counts()

Release_Date
2021    714
2018    530
2017    510
2019    500
2016    470
       ...
1925      1
1902      1
1920      1
1929      1
1930      1
Name: count, Length: 102, dtype: int64

In [16]:
df['Genre'] =df['Genre'].str.split(', ')

df['Genre']

0       [Action, Adventure, Science Fiction]
1                 [Crime, Mystery, Thriller]
2                                 [Thriller]
3       [Animation, Comedy, Family, Fantasy]
4         [Action, Adventure, Thriller, War]
                        ...
9832                          [Drama, Crime]
9833                                [Horror]
9834             [Mystery, Thriller, Horror]
9835                 [Music, Drama, History]
9836           [War, Drama, Science Fiction]
Name: Genre, Length: 9826, dtype: object

In [17]:
df=df.explode('Genre').reset_index(drop=True)

df.head()

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,8.3,Action
1,2021,Spider-Man: No Way Home,5083.954,8940,8.3,Adventure
2,2021,Spider-Man: No Way Home,5083.954,8940,8.3,Science Fiction
3,2022,The Batman,3827.658,1151,8.1,Crime
4,2022,The Batman,3827.658,1151,8.1,Mystery

In [18]:
df['Genre']=df['Genre'].astype('category')

df['Genre'].dtypes

CategoricalDtype(categories=['Action', 'Adventure', 'Animation', 'Comedy', 'Crime',
                  'Documentary', 'Drama', 'Family', 'Fantasy', 'History',
                  'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction',
                  'TV Movie', 'Thriller', 'War', 'Western'],
, ordered=False, categories_dtype=object)

In [19]:
df['Genre']

0                 Action
1              Adventure
2        Science Fiction
3                  Crime
4                Mystery
              ...
25787              Drama
25788            History
25789                War
25790              Drama
25791    Science Fiction
Name: Genre, Length: 25792, dtype: category
Categories (19, object): ['Action', 'Adventure', 'Animation', 'Comedy', ..., 'TV Movie', 'Thriller', 'War', 'Western']

In [20]:
df

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,8.3,Action
1,2021,Spider-Man: No Way Home,5083.954,8940,8.3,Adventure
2,2021,Spider-Man: No Way Home,5083.954,8940,8.3,Science Fiction
3,2022,The Batman,3827.658,1151,8.1,Crime
4,2022,The Batman,3827.658,1151,8.1,Mystery
...,...,...,...,...,...,...
25787,2021,The United States vs. Billie Holiday,13.354,152,6.7,Drama
25788,2021,The United States vs. Billie Holiday,13.354,152,6.7,History
25789,1984,Threads,13.354,186,7.8,War
25790,1984,Threads,13.354,186,7.8,Drama
25791,1984,Threads,13.354,186,7.8,Science Fiction

In [21]:
df['Genre'].value_counts()

Genre
Drama              3744
Comedy             3031
Action             2686
Thriller           2488
Adventure          1853
Romance            1476
Horror             1470
Animation          1438
Family             1414
Fantasy            1308
Science Fiction    1273
Crime              1242
Mystery             773
History             427
War                 308
Music               295
Documentary         215
TV Movie            214
Western             137
Name: count, dtype: int64

In [22]:
df.groupby('Genre')['Vote_Count'].sum()

C:\Users\ADmin\AppData\Local\Temp\ipykernel_9392\154460404.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Genre')['Vote_Count'].sum()

Genre
Action             8940179333114161001073131936539316013123184969...
Adventure          8940179310073728865393160691222422255845314110...
Animation          5076100737288217222243121631785843210002515886...
Comedy             5076737288313193217222252301631100421785843210...
Crime              1151331141610795231319349562667593509212761611...
Documentary        4557110549115519267134671861056974334320522131...
Drama              9524956213313142114322788544156320755184812767...
Family             5076737288217216311001785810005886855189012287...
Fantasy            5076114100288222422255845312110085689251588644...
History            3141848389210667117845353247635273475654127745...
Horror             8215214313121043210437544207300804233752189010...
Music              2172230281615355664219010710930168496521591923...
Mystery            1151821211544123001198423334425114398228831221...
Romance            2305621331156316801615390834481162501139686973...
Science Fiction    8940472665393160131210005158741442262372075240...
TV Movie           8113862975068556670920528919231194241908413299...
Thriller           1151122179333821206161079526531933184931321188...
War                1793271179210667975720852734183221093442012774...
Western            1631061192350803753132011452214744142374977518...
Name: Vote_Count, dtype: object

In [23]:
title=df[df['Popularity']==df['Popularity'].max()]['Title']

In [24]:
title

0    Spider-Man: No Way Home
1    Spider-Man: No Way Home
2    Spider-Man: No Way Home
Name: Title, dtype: object

In [25]:
genre=df[df['Popularity']==df['Popularity'].max()]['Genre']
genre

0             Action
1          Adventure
2    Science Fiction
Name: Genre, dtype: category
Categories (19, object): ['Action', 'Adventure', 'Animation', 'Comedy', ..., 'TV Movie', 'Thriller', 'War', 'Western']