In [1]:
import numpy as np
import pandas  as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('quikr_car.csv')

In [3]:
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [4]:
df['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [5]:
df.shape

(892, 6)

In [6]:
backup=df.copy()

In [7]:
df=df[df['year'].str.isnumeric()]

In [8]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [9]:
df['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '2003', '2004', '1995', '2002', '2001'], dtype=object)

In [10]:
df['year']=df['year'].astype('int32')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    int32
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int32(1), object(5)
memory usage: 42.8+ KB

In [12]:
df=df[df['Price'] !='Ask For Price']

In [13]:
df['Price']=df['Price'].str.replace(",","")

C:\Users\ADmin\AppData\Local\Temp\ipykernel_1072\2430177646.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price']=df['Price'].str.replace(",","")

In [14]:
df['Price']=df['Price'].astype(int)

C:\Users\ADmin\AppData\Local\Temp\ipykernel_1072\1259578919.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price']=df['Price'].astype(int)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int32
 3   Price       819 non-null    int64
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int32(1), int64(1), object(4)
memory usage: 41.6+ KB

In [16]:
df['kms_driven']=df['kms_driven'].str.replace("kms","")

C:\Users\ADmin\AppData\Local\Temp\ipykernel_1072\428301793.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['kms_driven']=df['kms_driven'].str.replace("kms","")

In [17]:
df['kms_driven']=df['kms_driven'].str.replace(",","")

C:\Users\ADmin\AppData\Local\Temp\ipykernel_1072\3648989641.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['kms_driven']=df['kms_driven'].str.replace(",","")

In [18]:
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel

In [19]:
df['kms_driven'].unique()

array(['45000 ', '40 ', '28000 ', '36000 ', '41000 ', '25000 ', '24530 ',
       '60000 ', '30000 ', '32000 ', '48660 ', '4000 ', '16934 ',
       '43000 ', '35550 ', '39522 ', '39000 ', '55000 ', '72000 ',
       '15975 ', '70000 ', '23452 ', '35522 ', '48508 ', '15487 ',
       '82000 ', '20000 ', '68000 ', '38000 ', '27000 ', '33000 ',
       '46000 ', '16000 ', '47000 ', '35000 ', '30874 ', '15000 ',
       '29685 ', '130000 ', '19000 ', '54000 ', '13000 ', '38200 ',
       '22000 ', '50000 ', '13500 ', '3600 ', '45863 ', '60500 ',
       '12500 ', '18000 ', '13349 ', '29000 ', '44000 ', '42000 ',
       '14000 ', '49000 ', '36200 ', '51000 ', '104000 ', '33333 ',
       '33600 ', '5600 ', '7500 ', '26000 ', '24330 ', '65480 ',
       '200000 ', '59000 ', '99000 ', '2800 ', '21000 ', '11000 ',
       '66000 ', '3000 ', '7000 ', '38500 ', '37200 ', '43200 ', '24800 ',
       '45872 ', '40000 ', '11400 ', '97200 ', '52000 ', '31000 ',
       '175430 ', '37000 ', '65000 ', '3350 ', '75000 ', '62000 ',
       '73000 ', '2200 ', '54870 ', '34580 ', '97000 ', '60 ', '80200 ',
       '3200 ', '0000 ', '5000 ', '588 ', '71200 ', '175400 ', '9300 ',
       '56758 ', '10000 ', '56450 ', '56000 ', '32700 ', '9000 ', '73 ',
       '160000 ', '58559 ', '57000 ', '170000 ', '80000 ', '6821 ',
       '23000 ', '34000 ', '1800 ', '400000 ', '48000 ', '90000 ',
       '12000 ', '69900 ', '166000 ', '122 ', '0 ', '36469 ', '7800 ',
       '24695 ', '15141 ', '59910 ', '100000 ', '4500 ', '129000 ',
       '300 ', '131000 ', '111111 ', '59466 ', '25500 ', '44005 ',
       '2110 ', '43222 ', '100200 ', '65 ', '140000 ', '103553 ',
       '58000 ', '120000 ', '49800 ', '100 ', '81876 ', '6020 ', '55700 ',
       '18500 ', '53000 ', '35500 ', '22134 ', '1000 ', '8500 ', '87000 ',
       '6000 ', '8000 ', '55800 ', '56400 ', '72160 ', '11500 ',
       '133000 ', '2000 ', '88000 ', '65422 ', '117000 ', '150000 ',
       '10750 ', '6800 ', '9800 ', '57923 ', '30201 ', '6200 ', '37518 ',
       '24652 ', '383 ', '95000 ', '3528 ', '52500 ', '47900 ', '52800 ',
       '195000 ', '48008 ', '48247 ', '9400 ', '64000 ', '2137 ',
       '10544 ', '147000 ', '90001 ', '48006 ', '74000 ', '85000 ',
       '29500 ', '39700 ', '67000 ', '19336 ', '60105 ', '45933 ',
       '102563 ', '28600 ', '41800 ', '116000 ', '42590 ', '7400 ',
       '54500 ', '76000 ', '00 ', '11523 ', '38600 ', '95500 ', '37458 ',
       '85960 ', '12516 ', '30600 ', '2550 ', '62500 ', '69000 ',
       '28400 ', '68485 ', '3500 ', '85455 ', '63000 ', '1600 ', '77000 ',
       '26500 ', '2875 ', '13900 ', '1500 ', '2450 ', '1625 ', '33400 ',
       '60123 ', '137495 ', '91200 ', '146000 ', '100800 ', '2100 ',
       '2500 ', '132000 ', 'Petrol'], dtype=object)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int32
 3   Price       819 non-null    int64
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int32(1), int64(1), object(4)
memory usage: 41.6+ KB

In [21]:
df=df[(df['kms_driven'] !='Petrol') & (df['kms_driven'] != 'NAN')]

In [22]:
df['kms_driven']= df['kms_driven'].astype(int)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int32
 3   Price       817 non-null    int64
 4   kms_driven  817 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int32(1), int64(2), object(3)
memory usage: 41.5+ KB

In [24]:
df=df[~df['fuel_type'].isna()]

In [25]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [26]:
df['name']=df['name'].str.split(" ").str.slice(0,3).str.join(" ")

In [27]:
df

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [28]:
df=df.reset_index(drop=True)

In [29]:
df

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [30]:
df

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [31]:
df.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [32]:
df=df[df['Price']<6e6].reset_index(drop=True)

In [33]:
df

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [34]:
X=df.drop(columns=['Price'])
y=df['Price']

In [35]:
X.head()

                     name   company  year  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2       Hyundai Grand i10   Hyundai  2014       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014       36000    Diesel
4               Ford Figo      Ford  2012       41000    Diesel

In [36]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [37]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [38]:
ohe=OneHotEncoder()
ohe.fit(X[['name','company','fuel_type']])

OneHotEncoder()

In [39]:
ctf=make_column_transformer(
    (OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']), remainder='passthrough')

In [40]:
model=LinearRegression()

In [41]:
pipe=make_pipeline(ctf,model)

In [42]:
pipe.fit(X_train,y_train)

C:\Users\ADmin\AppData\Roaming\Python\Python313\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [43]:
pipe.score(X_test,y_test)

0.61053057219731

In [48]:
scores=[]

for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=i)
    model=LinearRegression()
    pipe=make_pipeline(ctf,model)
    pipe.fit(X_train,y_train)
    scores.append(pipe.score(X_test,y_test))

In [49]:
np.argmax(scores)

np.int64(433)

In [50]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=np.argmax(scores))
model=LinearRegression()
pipe=make_pipeline(ctf,model)
pipe.fit(X_train,y_train)
pipe.score(X_test,y_test)

0.8457059012561223

In [52]:
import pickle
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))